global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using ReLogic.Graphics;
global using SilkyUIFramework.Attributes;
global using SilkyUIFramework.BasicElements;
global using SilkyUIFramework.Extensions;
global using SilkyUIFramework.Graphics2D;
global using SilkyUIFramework.Helper;
global using System.Reflection;
global using Terraria;
global using Terraria.Audio;
global using Terraria.GameContent;
global using Terraria.GameInput;
global using Terraria.ID;
global using Terraria.ModLoader;
global using Terraria.UI;
global using PlainSnippet = Terraria.GameContent.UI.Chat.PlainTagHandler.PlainSnippet;